name: Build & Deploy

on:
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed
    branches: [ main ]

jobs:
  gradle-build:
    name: gradle build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Temporarily save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: gradle-build
        path: build
        retention-days: 1
        
  docker:
    name: deploy docker image
    runs-on: ubuntu-latest
    needs: gradle-build
    env:
      REPO: qriositylog/algorio-ci-test
      
    steps:
    - uses: actions/checkout@v2
    - name: Get gradle built artifact
      uses: actions/download-artifact@v2
      with:
        name: gradle-build
        path: build
        
    - name: Docker Hub Sign-in
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Building Docker Image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} .
      
    - name: Publish Docker Image
      run: docker push $REPO
