name: Publish to GCR

# This workflow publishes Docker image to GitHub Container Registry

on:
  release:
    types: [published]

jobs:
  gradle-build:
    name: gradle build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Temporarily save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: gradle-build
        path: build
        retention-days: 1
        
        
  build-and-publish-latest:
    runs-on: ubuntu-latest
    needs: gradle-build

    steps:
    - uses: actions/checkout@v2
    - name: Get gradle built artifact
      uses: actions/download-artifact@v2
      with:
        name: gradle-build
        path: build

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: algorio-backend # tag will be automatically set to latest
